# Generated by Django 3.2.9 on 2022-08-31 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm', models.IntegerField()),
                ('kkm', models.IntegerField()),
                ('mis', models.IntegerField()),
                ('eis', models.IntegerField()),
                ('ss', models.IntegerField()),
                ('tt', models.IntegerField()),
                ('et', models.IntegerField()),
                ('ik', models.IntegerField()),
                ('ek', models.IntegerField()),
                ('tk', models.IntegerField()),
                ('tpg', models.IntegerField()),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
