# Generated by Django 3.2.9 on 2022-09-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0005_alter_rapor_guncelleme_tarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapor',
            options={'verbose_name': 'Rapor', 'verbose_name_plural': 'Raporlar'},
        ),
        migrations.RenameField(
            model_name='rapor',
            old_name='ekleme_tarihi',
            new_name='rapor_olusturma_tarihi',
        ),
    ]
