# Generated by Django 3.2.9 on 2022-09-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0007_auto_20220901_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='raporss',
            field=models.CharField(default='Rapor', max_length=5),
        ),
    ]
