# Generated by Django 3.2.9 on 2022-09-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0014_remove_rapor_guncelleme_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapor',
            name='image',
        ),
        migrations.AddField(
            model_name='rapor',
            name='yapilan_is_foto',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
