# Generated by Django 3.2.9 on 2022-09-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0015_auto_20220902_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='yapilan_is_foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/'),
        ),
    ]
